sensv1: sensv1.o getAccel.o getGyro.o getCompass.o senserver.h burstAccel.o proclist.o burstGyro.o burstCompass.o moveAccel.o bluegetAccel.o bluemoveAccel.o
			gcc -o sensv1 sensv1.c getAccel.o getGyro.o getCompass.o senserver.h burstAccel.o proclist.o burstGyro.o burstCompass.o moveAccel.o bluegetAccel.o bluemoveAccel.o -lwiringPi

sensv1.o: sensv1.c
			gcc -c sensv1.c

getAccel.o: getAccel.c
			gcc -c getAccel.c

getGyro.o: getGyro.c
			gcc -c getGyro.c

getCompass.o: getCompass.c
			gcc -c getCompass.c

burstAccel.o: burstAccel.c
			gcc -c burstAccel.c

burstGyro.o: burstGyro.c
			gcc -c burstGyro.c

burstCompass.o: burstCompass.c
			gcc -c burstCompass.c

moveAccel.o: moveAccel.c
			gcc -c moveAccel.c

bluegetAccel.o: bluegetAccel.c
			gcc -c bluegetAccel.c

bluemoveAccel.o: bluemoveAccel.c
			gcc -c bluemoveAccel.c

proclist.o: proclist.c
			gcc -c proclist.c
